export const CSS_STYLE_RULE_SET_SELECTOR_TEXT = "CSS_STYLE_RULE_SET_SELECTOR_TEXT"; 
export const CSS_STYLE_RULE_SET_STYLE = "CSS_STYLE_RULE_SET_STYLE"; 
export const CSS_STYLE_RULE_SET_STYLE_PROPERTY = "CSS_STYLE_RULE_SET_STYLE_PROPERTY";
export const CSS_PARENT_INSERT_RULE = "CSS_PARENT_INSERT_RULE";
export const CSS_PARENT_DELETE_RULE = "CSS_PARENT_DELETE_RULE";
export const CSS_PARENT_MOVE_RULE   = "CSS_PARENT_MOVE_RULE";
export const CSS_INSERT_CSS_RULE_TEXT   = "CSS_INSERT_CSS_RULE_TEXT";