{
  const {
    AllSelectorExpression,
    TagNameSelectorExpression,
  } = require("./ast");

  function position() {
    return {
      start:peg$savedPos,
      end:peg$currPos
    };
  }
}

Start = ElementSelector

ElementSelector = TagNameSelector/AllSelector

TagNameSelector = Word {
  return new TagNameSelectorExpression(text(), position());
}
AllSelector = "*" {
  return new AllSelectorExpression(position());
}

Word = [a-zA-Z]+ { text() }