// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7aa3ecd72efc77a80aac3782a511a40b2aba5b47/get-port/get-port.d.ts
declare module "get-port" {
    var getPort: () => PromiseLike<number>
    export = getPort;
}
