// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/sprintf/sprintf.d.ts
declare module "sprintf" {
	export function sprintf(fmt: string, ...args: any[]): string;
	export function vsprintf(fmt: string, args: any[]): string;
}
