"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CSS_STYLE_RULE_SET_SELECTOR_TEXT = "CSS_STYLE_RULE_SET_SELECTOR_TEXT";
exports.CSS_STYLE_RULE_SET_STYLE = "CSS_STYLE_RULE_SET_STYLE";
exports.CSS_STYLE_RULE_SET_STYLE_PROPERTY = "CSS_STYLE_RULE_SET_STYLE_PROPERTY";
exports.CSS_PARENT_INSERT_RULE = "CSS_PARENT_INSERT_RULE";
exports.CSS_PARENT_DELETE_RULE = "CSS_PARENT_DELETE_RULE";
exports.CSS_PARENT_MOVE_RULE = "CSS_PARENT_MOVE_RULE";
exports.CSS_INSERT_CSS_RULE_TEXT = "CSS_INSERT_CSS_RULE_TEXT";
//# sourceMappingURL=constants.js.map